version: '3.8'

# Common build definition using YAML anchors
x-node-build: &node-build
  build:
    context: .
    dockerfile: Dockerfile

services:
  node1:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node1_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node1:/app/logs
    environment:
      - NODE_NAME=node1
      - DEVICE_ID=SG1001KE01
      - RUST_LOG=info
      - MDNS_PORT=5354
      - RUST_BACKTRACE=1
    network_mode: host
    command: ["SG1001KE01"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node2:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node2_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node2:/app/logs
    environment:
      - NODE_NAME=node2
      - DEVICE_ID=SC1002KE02
      - RUST_LOG=info
      - MDNS_PORT=5355
      - RUST_BACKTRACE=1
    network_mode: host
    command: ["SC1002KE02"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node3:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node3_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node3:/app/logs
    environment:
      - NODE_NAME=node3
      - DEVICE_ID=SGC1003KE03
      - RUST_LOG=info
      - MDNS_PORT=5356
      - RUST_BACKTRACE=1
    network_mode: host
    command: ["SGC1003KE03"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node4:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node4_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node4:/app/logs
    environment:
      - NODE_NAME=node4
      - DEVICE_ID=SC1052US03
      - RUST_LOG=info
      - MDNS_PORT=5357
      - RUST_BACKTRACE=1
    network_mode: host
    command: ["SC1052US03"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node5:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node5_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node5:/app/logs
    environment:
      - NODE_NAME=node5
      - DEVICE_ID=SG1004KE04
      - RUST_LOG=info
      - MDNS_PORT=5358
      - RUST_BACKTRACE=1
    network_mode: host
    command: ["SG1004KE04"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node6:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node6_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node6:/app/logs
    environment:
      - NODE_NAME=node6
      - DEVICE_ID=SG1005NG01
      - RUST_LOG=info
      - MDNS_PORT=5359
    network_mode: host
    command: ["SG1005NG01"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node7:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node7_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node7:/app/logs
    environment:
      - NODE_NAME=node7
      - DEVICE_ID=SC1006NG02
      - RUST_LOG=info
      - MDNS_PORT=5360
    network_mode: host
    command: ["SC1006NG02"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node8:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node8_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node8:/app/logs
    environment:
      - NODE_NAME=node8
      - DEVICE_ID=SGC1007NG03
      - RUST_LOG=info
      - MDNS_PORT=5361
    network_mode: host
    command: ["SGC1007NG03"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node9:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node9_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node9:/app/logs
    environment:
      - NODE_NAME=node9
      - DEVICE_ID=SG1008ZA01
      - RUST_LOG=info
      - MDNS_PORT=5362
    network_mode: host
    command: ["SG1008ZA01"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  node10:
    <<: *node-build
    image: p2p-node-image
    volumes:
      - ./identities/node10_config.yaml:/app/config.yaml
      - ./identities/devices.yaml:/app/devices.yaml
      - ./logs/node10:/app/logs
    environment:
      - NODE_NAME=node10
      - DEVICE_ID=SC1009ZA02
      - RUST_LOG=info
      - MDNS_PORT=5363
    network_mode: host
    command: ["SC1009ZA02"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
