version: '3.8'

services:
  # Bootstrap service for generating node keys and principals
  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile
    image: power-logger:latest
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./script:/app/script:ro
    environment:
      - IC_URL=http://localhost:4943

    network_mode: host
    command: /bin/sh -c "echo 'Bootstrap image built successfully'"

  # Node 1
  node1:
    image: power-logger:latest
    container_name: power-node-1
    ports:
      - "33334:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node1/data:/app/data
      - ./nodes/node1/logs:/app/logs
    environment:
      - NODE_ID=1
      - NODE_NAME=PowerNode1
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 2
  node2:
    image: power-logger:latest
    container_name: power-node-2
    ports:
      - "33335:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node2/data:/app/data
      - ./nodes/node2/logs:/app/logs
    environment:
      - NODE_ID=2
      - NODE_NAME=PowerNode2
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 3
  node3:
    image: power-logger:latest
    container_name: power-node-3
    ports:
      - "33336:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node3/data:/app/data
      - ./nodes/node3/logs:/app/logs
    environment:
      - NODE_ID=3
      - NODE_NAME=PowerNode3
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 4
  node4:
    image: power-logger:latest
    container_name: power-node-4
    ports:
      - "33337:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node4/data:/app/data
      - ./nodes/node4/logs:/app/logs
    environment:
      - NODE_ID=4
      - NODE_NAME=PowerNode4
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 5
  node5:
    image: power-logger:latest
    container_name: power-node-5
    ports:
      - "33338:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node5/data:/app/data
      - ./nodes/node5/logs:/app/logs
    environment:
      - NODE_ID=5
      - NODE_NAME=PowerNode5
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 6
  node6:
    image: power-logger:latest
    container_name: power-node-6
    ports:
      - "33339:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node6/data:/app/data
      - ./nodes/node6/logs:/app/logs
    environment:
      - NODE_ID=6
      - NODE_NAME=PowerNode6
      - RUST_LOG=info
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 7
  node7:
    image: power-logger:latest
    container_name: power-node-7
    ports:
      - "33340:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node7/data:/app/data
      - ./nodes/node7/logs:/app/logs
    environment:
      - NODE_ID=7
      - NODE_NAME=PowerNode7
      - RUST_LOG=info
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 8
  node8:
    image: power-logger:latest
    container_name: power-node-8
    ports:
      - "33341:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node8/data:/app/data
      - ./nodes/node8/logs:/app/logs
    environment:
      - NODE_ID=8
      - NODE_NAME=PowerNode8
      - RUST_LOG=info
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 9
  node9:
    image: power-logger:latest
    container_name: power-node-9
    ports:
      - "33342:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node9/data:/app/data
      - ./nodes/node9/logs:/app/logs
    environment:
      - NODE_ID=9
      - NODE_NAME=PowerNode9
      - RUST_LOG=info
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

  # Node 10
  node10:
    image: power-logger:latest
    container_name: power-node-10
    ports:
      - "33343:33334"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./devices.yaml:/app/devices.yaml:ro
      - ./nodes/node10/data:/app/data
      - ./nodes/node10/logs:/app/logs
    environment:
      - NODE_ID=10
      - NODE_NAME=PowerNode10
      - RUST_LOG=info
      - IC_URL=http://localhost:4943
    network_mode: host
    depends_on:
      - bootstrap

networks:
  power-network:
    driver: bridge 